---
title: "ACA228"
output:
  distill::distill_article: 
    fig_width: 1
    toc_float: false  
---

<center>

# Modelos de Regressão e Previsão

## 2021.2

**ATENÇÃO: as aulas começarão no dia 23 de novembro**

</center>



As datas das provas e apresentação do trabalho já estão definidas. Programe-se com antecedência. 

- $P_1$: **08-02-2022**
- $P_2$: **24-02-2022**  



</br>

`r emo::ji("pencil")` [Plano de Ensino](2021-2/Plano_ACA228_2021-2.pdf) 

`r emo::ji("pause")` [YouTube Channel](https://www.youtube.com/playlist?list=PLrqJCLOY0EkB-e9LLuROY5FQBD3wCzDNi) 

`r emo::ji("teacher")` [Google Classroom](https://classroom.google.com/c/NDI5NTM4Njk3Mzk2?cjc=a7o6ecg)  (Código da Turma caso precisarem: a7o6ecg)

</br>

**Horários**    

`r emo::ji("calendar")` Terças e Quintas das 18:30 às 20:10 


**Monitorias**

- **Monitora:** Brenda Barros Fabricio
- **Horario:** Segundas das 19 até as 21 horas.
- **Email:** brendabf04 _at_ gmail _dot_ com (substitua _at_ com `@` e _dot_ com `.`)
- Mais detalhes da monitoria no Google Class.


### **Material e Aulas**

- [Livro de R em português](http://leg.ufpr.br/Rpira/Rpira.pdf) 
- [Livro Online: R for Data Science](https://r4ds.had.co.nz) 
- [Apêndice do livro texto](MRP/Apendice_Livro.pdf) 


### **Cronograma**


| Data  | Assunto                | Slides      | Video |
|:-----:|:-----------------------|:----------:|--------|
| 23-11-2021     | Intro + EDA  | [Link](https://ctruciosm.github.io/ACA-228/ACA228_01) | [Link](https://youtu.be/YhIrYoy7HO4) | 
| 25-11-2021     | **Lab:** [Introdução ao R](https://ctruciosm.github.io/ACA-228/LabR_01)  | [Link](2021-2/LabR_01.pdf)  | [Link](https://youtu.be/gYr33m1Mlbw) | 
| 30-11-2021     | Regressão Linear Simples (RLS)   | [Link](2021-2/ACA228_03.pdf)  | [Link](https://youtu.be/tbNeMK5VOiU)  | 
| 02-12-2021     | **Lab:** [Tabelas, Gráficos e RLS](https://ctruciosm.github.io/ACA-228/LabR_02) | [Link](2021-2/LabR_02.pdf)  | [Link](https://youtu.be/55bn6vLcxUk)  | 
| 07-12-2021     | RLS: Interpretação e Propriedades  | [Link](2021-2/ACA228_05.pdf) | [Link](https://www.youtube.com/watch?v=hoXfen8FBaI&list=PLrqJCLOY0EkD6oErQRlAN6gkviRjvyVTj&index=5)  | 
| 09-12-2021     | **Lab:** [Visualização de dados e RLS](https://ctruciosm.github.io/ACA-228/LabR_03) | [Link](2021-2/LabR_03.pdf)  | [Link](https://youtu.be/Smz5fP06A-k) | 
| 14-12-2021     | Regressão Linear Multipla (RLM)  | [Link](2021-2/ACA228_07.pdf) | [Link](https://www.youtube.com/watch?v=p_lwwEX2wF8&list=PLrqJCLOY0EkC9fccnL-a2c0hF5sarIVwm&index=7)  | 
| 16-12-2021     | MRLM: Inferência  | [Link](2021-2/ACA228_08.pdf) | [Link](https://youtu.be/6jUdkL1EcN4)  | 
| `r emo::ji("christmas")` `r emo::ji("Christmas")` `r emo::ji("christmas")`   |    **Feliz Natal e Ótimo 2022!**     |  |  | 
| 04-01-2022     | **Lab:** [Manipulação de dados e Análide de Regressão com R](https://ctruciosm.github.io/ACA-228/LabR_04)  | [Link](2021-2/LabR_04.pdf)  | [Link](https://youtu.be/HoYS35tJlEs) |
| 06-01-2022     | MRLM: Tópicos adicionais   | [Link](2021-2/ACA228_10.pdf) | [Link](https://youtu.be/trgnj_M5ZCQ) | 
| 11-01-2022     | MRLM: variáveis qualitativas e efeito de interação | [Link](2021-2/ACA228_11.pdf) | [Link](https://www.youtube.com/watch?v=7T135j3foPM&list=PLrqJCLOY0EkD6oErQRlAN6gkviRjvyVTj&index=10)  | 
| 13-01-2022     | **Lab:** Análide de Regressão com R  |  | [Link](https://youtu.be/9F13w3LO_VI) | 
| 18-01-2022     | MRLM: verificação das hipóteses  | [Link](2021-2/ACA228_13.pdf) | [Link](https://www.youtube.com/watch?v=YfmrhVDZrko&list=PLrqJCLOY0EkD6oErQRlAN6gkviRjvyVTj&index=12) | 
| 25-01-2022     | MRLM: verificação das hipóteses II  | [Link](2021-2/ACA228_14.pdf) | [Link](https://www.youtube.com/watch?v=a2gh_DRyxGU&list=PLrqJCLOY0EkD6oErQRlAN6gkviRjvyVTj&index=13) | 
| 27-01-2022     | **Lab:** Análide de Regressão com R  |  | [Link](https://www.youtube.com/watch?v=NydVTtabjjs&list=PLrqJCLOY0EkD6oErQRlAN6gkviRjvyVTj&index=15&t=2s) | 
| 01-02-2022     | [Intro às Séries Temporais](https://ctruciosm.github.io/ACA-228/ACA228_ST_01) |  | [Link](https://www.youtube.com/watch?v=0tDvFLhCqPs&list=PLrqJCLOY0EkD6oErQRlAN6gkviRjvyVTj&index=16&t=3031s)  | 
| 03-02-2022     | [Séries Temporais: Fundamentos](https://ctruciosm.github.io/ACA-228/ACA228_ST_02) |  | [Link](https://youtu.be/LjjorLeg1QE)  | 
| **08-02-2022**     | $P_1$   |  |  | 
| 10-02-2022     | [ST: Avaliando modelos](https://ctruciosm.github.io/ACA-228/ACA228_ST_03)  |  | [Link](https://youtu.be/B1ApoLxjoK0)   | 
| **SIAc**     | [**Semana da Integração Acadêmica**](https://siac.ufrj.br) Participe! `r emo::ji("student")`  `r emo::ji("student")` |   |  | 
| 15-02-2022     | [Regressão e séries temporais](https://ctruciosm.github.io/ACA-228/ACA228_ST_04) |  |[Link](https://www.youtube.com/watch?v=Cs8iqxccdqI&list=PLrqJCLOY0EkD6oErQRlAN6gkviRjvyVTj&index=19) | 
| 17-02-2022     | [Regressão e séries temporais II](https://ctruciosm.github.io/ACA-228/ACA228_ST_05) |  | [Link](https://www.youtube.com/watch?v=xiviIGjNp-8&list=PLrqJCLOY0EkD6oErQRlAN6gkviRjvyVTj&index=20)  | 
| 22-02-2022     | [Suavização exponencial](https://ctruciosm.github.io/ACA-228/ACA228_ST_06) |    | [Link](https://www.youtube.com/watch?v=iCTl2CL381c&list=PLrqJCLOY0EkD6oErQRlAN6gkviRjvyVTj&index=21) | 
| **24-02-2022**     | $P_2$ |  |   | 
| 10-03-2022    | Exame de recuperação|  |   | 


<center>

> Nesse tempo de pandemia sei que as coisas não estão fáceis. Se precisar conversar com alguém, seja o assunto que for,  pode contar comigo. 

</center>



---- 