---
title: "Carlos Trucíos" #espaço:\_\_\_\_\_ 
output:
  html_document:
    fig_width: 1
---


<link href="site_libs/academicons-1.8.6/css/academicons.min.css" rel="stylesheet" />
----


<div class="column-left">
![<a href= https://github.com/ctruciosm > <i class="fa fa-github-square fa-2x" aria-hidden="true" link =  ></i></a>
<a href= https://www.linkedin.com/in/ctrucios/ > <i class="fa fa-linkedin-square fa-2x" aria-hidden="true" link =  ></i></a>
<a href= http://lattes.cnpq.br/9315014843913122 > <i class="ai ai-lattes-square fa-2x" aria-hidden="true"></i> </a>
<a href= https://scholar.google.com/citations?user=HEdXeQkAAAAJ > <i class="ai ai-google-scholar-square fa-2x" aria-hidden="true"></i></a>
<a href= https://orcid.org/0000-0001-8746-8877 > <i class="ai ai-orcid-square fa-2x" aria-hidden="true"></i></a>
<a href= https://www.researchgate.net/profile/Carlos_Trucios > <i class="ai ai-researchgate-square fa-2x" aria-hidden="true"></i></a>](imagens/foto_ctrucios.jpeg)

**CONTACT** </br>
<i class="fa fa-envelope" aria-hidden="true"></i> 
carlos.trucios _at_ </i> facc.ufrj.br

</div>
<div class="column-right">

I am Assistant (tenure track) Professor of Quantitative Methods in the Faculty of Business Administration and Accounting (FACC) at the Federal University of Rio de Janeiro (UFRJ), Brazil. 


I hold a Ph.D in Statistics from the University of Campinas (Brazil) and my research interests are risk management, portfolio allocation, volatility forecasting, robust statistics, and statistical learning. 

I received the y-BIS Best Paper Award (ISBIS 2016 - Barcelona, Spain), IASC-ERS Young Researchers Award (COMPSTAT 2018 - Iasi, Romania), and also the best paper Award in the 4th Latin American Conference for Statistical Computing (LACSC 2019 - Guayaquil, Ecuador). 


Before I joined the Federal University of Rio de Janeiro, I worked in Brazilian companies as a Data Science Specialist, Data Science Coordinator, and Data Scientist Consultant. 



Currently, my goal is to apply statistical learning techniques on Business, Economic and Finance as well as develop new volatility forecasting procedures in high-dimensional and high-frequency data.
</span>
</br>

<span style="color:darkgreen"> <b>*Forthcoming events: * </b></span> </br> 
</i> X Encuentro Nacional de Matemáticas y Estadística, 2021 </br>
</i> Latin American Conference on Statistical Computing (LACSC 2021), April 19 to April 21, 2021 </br>

</br>

</div>



</br>
</br>



<div class="column-left2">
<span style="color:darkgreen"> **Education** </span> </br> 

<i class="fa fa-graduation-cap" aria-hidden="true"></i> PhD in Statistics </br> <small> University of Campinas, 2016. Brazil </small> </br>
<i class="fa fa-graduation-cap" aria-hidden="true"></i> Visiting PhD Student </br> <small> University Carlos III de Madrid, 2014. Spain </small> </br>
<i class="fa fa-graduation-cap" aria-hidden="true"></i>   MSc in Statistics </br> <small> University of Campinas, 2012. Brazil </small>  </br>
<i class="fa fa-graduation-cap" aria-hidden="true"></i>   BSc in Statistics </br> <small> National University of San Marcos, 2009. Peru </small> 
</div>


<div class="column-center2">
<span style="color:darkgreen"> **Past positions** </span> </br> 

<i class="fa fa-graduation-cap" aria-hidden="true"></i> Postdoctoral Researcher </br> <small> São Paulo School of Economics-FGV, </br> 2016-2019. Brazil </small> </br>
<i class="fa fa-graduation-cap" aria-hidden="true"></i> Visiting Postdoctoral Researcher </br> <small> Université libre de Bruxelles, </br> 2018. Belgium </small> </br>
<i class="fa fa-graduation-cap" aria-hidden="true"></i> Visiting Professor </br> <small> Federal University of ABC, </br> 2020. Brazil </small> 
</div>

<div class="column-right2">
<span style="color:darkgreen"> **Interests** </span> </br> 

<i class="fa fa-graduation-cap" aria-hidden="true"></i> Bootstrap procedures for dependent data </br> 
<i class="fa fa-graduation-cap" aria-hidden="true"></i> High dimensional data </br> 
<i class="fa fa-graduation-cap" aria-hidden="true"></i> Risk measures and portfolio allocation </br> 
<i class="fa fa-graduation-cap" aria-hidden="true"></i> Robust procedures and outliers </br> 
<i class="fa fa-graduation-cap" aria-hidden="true"></i> Statistical learning for business and financial econometrics </br> 
</div>





