---
title: "Introdução à Probabilidade e Estatística"
output:
  html_document:
    fig_width: 1
    toc_float: false    
---


**Notas Finais e Conceitos**

[Notas](IPE/IPE_QS_2020_ALUNOS.xls) 
[Gabarito P2](IPE/P2.pdf) 


**P2**

A $P_2$ acontecerá pelo google class e será liberada no domingo **06/12/2020** por volta do meio dia até a quarta feira **08/12/2020** às 23:59 (mais de 72 horas).

Dicas: 

- Fiquem atentos se a v.a. é continua o discreta
- Vejam sempre quais valores a v.a. pode assumir (desde 0?, desde 1? a reta real toda?)
- Estudem, já falta pouco!




**Notas atualizadas até a Lista 2**
[Lista 2](IPE/Lista2.pdf)  - 
[Gabarito](IPE/Gabarito_Lista2.pdf)  - 
[Notas](IPE/IPE_QS_2020_L1P1L2.xls) 


**As notas da P1 e da Lista 1 (corrigida) já estão disponíveis**

[Gabarito da P1](IPE/P1.pdf) - 

**Lista 1**

[Lista 1](IPE/Lista1.pdf) - 
[Gabarito](IPE/Gabarito_Lista1.pdf) - 



**Links importantes**

[Plano de Ensino](IPE/PlanoEnsino.pdf) 

[YouTube Channel](https://www.youtube.com/channel/UCrvm4mM1eoOn5WWCs08_-zg) 

[Conferenciaweb RNP](https://conferenciaweb.rnp.br/webconf/carlos-193)  (As aulas serão transmitidas por esse link nos dias e horários correspondentes a cada turma)

**Google Classroom**

- [Turma: NA8BIN0406-15SA](https://classroom.google.com/c/MTYxOTg3MTc4NTQ3?cjc=rgcl32o)
- [Turma: NB8BIN0406-15SA](https://classroom.google.com/c/MTYxOTg3MTc4Njg0?cjc=d45bfga)


**Horários**

- **NA8BIN0406-15SA:** segunda das 21:00 às 23:00 (semanal); quarta das 19:00 às 21:00 (quinzenal II).
- **NB8BIN0406-15SA:** segunda das 19:00 às 21:00 (semanal); quarta das 21:00 às 23:00 (quinzenal II). 



**Monitorias**

Horários de atendimento:

- Gabriel - Segunda-Feira das 17h às 19h;
- Gabriel - Terça-Feira das 17h às 19h;
- Mateus - Quarta-Feira das 14h às 16h;
- Mateus - Sexta-Feira das 16h às 18h.

Os atendimentos serão por email, facebook, moodle e alguma ferramenta remota.

O email do Gabriel é: g.tavares@aluno.ufabc.edu.br e link do conf web: https://conferenciaweb.rnp.br/webconf/gabriel-78

Do Mateus em princípio será: mateusborgiani@gmail.com ainda não temos o link para atendimento remoto


----


### **Aulas**



| Semana | Assunto                     | Data       | Video | Slides | Extras |
|--------|-----------------------------|------------|-------|--------|--------|
| 1      | Análise Combinatória  1     | 2020-09-21 | [Link](https://youtu.be/ULVoVQF9LQQ)  | [Link](IPE/Semana01_Aula01.pdf)  | [Link](https://www.math.tecnico.ulisboa.pt/~dpaulino/Combinatoria.pdf)   |
| 2      | Análise Combinatória  2     | 2020-09-28 | [Link](https://youtu.be/T8JZjRZE9go)  | [Link](IPE/Semana02_Aula01.pdf)  | [Link](https://youtu.be/7QKiLZGr_Io)  |
| 2      | Probabilidade 1     | 2020-09-30 | [Link](https://youtu.be/u4JqFOlH8oo)  | [Link](IPE/Semana02_Aula02.pdf)  | -  |
| 3      | Probabilidade 2     | 2020-10-05 | [Link](https://youtu.be/tHswU2eiYYU)  | [Link](IPE/Semana03.pdf)  | -  |
| 4      | Probabilidade Conditional 1     | 2020-10-12 | [Link](https://youtu.be/WF7baXvOWEQ)  | [Link](IPE/Semana04_Aula01.pdf)  | -  |
| 4      | Probabilidade Conditional 2     | 2020-10-14 |  [Link](https://www.youtube.com/watch?v=Pti64rWtwlc&list=PLrqJCLOY0EkD3NrhtUWysruqbk7Lj5bB_&index=7&t=2113s) | [Link](IPE/Semana04_Aula02.pdf)  | -  | 
| 5      | Revisão     | 2020-10-19 |   | - | -  |
| 6      | Prova     | 2020-10-26 |   | - | -  |
| 6      | Variáveis aleatórias 1    | 2020-10-28 | [Link](https://youtu.be/wDQ4JPF1syo)  | [Link](IPE/Semana06.pdf)  | [Link](https://www.probabilitycourse.com/chapter3/3_1_1_random_variables.php)  |
| 7      | Variáveis aleatórias 2    | 2020-11-02 | [Link](https://youtu.be/PTmKMJxy164)  | [Link](IPE/Semana07.pdf) | [Binomial](http://www-eio.upc.es/teaching/pe/www.computing.dcu.ie/~jhorgan/chapter11slides.pdf) - [Poisson](http://www-eio.upc.es/teaching/pe/www.computing.dcu.ie/~jhorgan/chapter13slides.pdf)  |
| 8      | Variáveis aleatórias 3    | 2020-11-09 | [Link](https://youtu.be/Mia1tO5DNF8)  | [Link](IPE/Semana08_Aula1.pdf) |   |
| 8      | Variáveis aleatórias 4    | 2020-11-11 | [Link](https://youtu.be/KuTj-iileao)  | [Link](IPE/Semana08_Aula2.pdf) |   |
| 9      | Distribuição conjunta   | 2020-11-16 |  [Link](https://youtu.be/T_zUBmx_UMM)  | [Link](IPE/Semana09.pdf) |   |
| 10      | Teorema Central do Limite    | 2020-11-23 | [Link](https://youtu.be/oyCKahJawP0) - [Simulação](https://youtu.be/0dRTWcv7VBE)   | [Link](IPE/Semana10.pdf) |   |
| 10      | Estatística Descritiva    | 2020-11-26 | [Link](https://youtu.be/MCojvBThexU) | [Link](IPE/Semana10_Aula02.pdf) | [Link](https://www.cesadufs.com.br/ORBI/public/uploadCatalago/14435324022014Bioestatistica_Aula_02.pdf)  |











---- 
