---
title: "ME414D"
output:
  distill::distill_article: 
    fig_width: 1
    toc_float: false  
---

<center>

# Estatística para Experimentalistas

## 2025.2

</center>

### Datas Importantes


- **30/09:** Prova 1.
- **27/11:** Prova 2.
- **09/12:** Exame.


</br>

### Informações 

- `r emo::ji("pencil")` [Plano de desenvolvimento (PDD)](documentos/ME414D_Ementa_2025S2.pdf).
- `r emo::ji("teacher")` [Google Classroom  (Código da Turma caso precisarem: womjcsu)](https://classroom.google.com/c/Nzk4NzY1MDAyODcy?cjc=hovpkijl)
- `r emo::ji("calendar")` Terças e quintas-feiras das 8h às 10h no PB16



### Referência Bibliográficas

- Anderson, D. R; Sweeney, D. J.; e Williams, T. A. (2008). Estatística Aplicada à Administração e Economia. 2 edição. Cengage Learning
- [Ross, S. M. (2010). Introductory Statistics](http://www.sciencedirect.com/science/book/9780123743886)
- [Diez, D. M.; Barr, C. D.; Çetinkaya-Rundel, M. (2015).  OpenIntro Statistics](https://drive.google.com/file/d/0B-DHaDEbiOGkY1FCdEJFNGV1Ym8/view)
- Bussab, W.O. e Morettin, P.A. (2017). Estatística Básica. 9a edição.
- Magalhães, M.N. e de Lima, A.C.P. (2001). Noções de Probabilidade e Estatística. IME-USP.




### **Cronograma**



| Aula  | Tópico                 | Slides | Adicional  |
|:-----:|:-----------------------|--------|------------|
| 01      | Introdução    | [Link](http://me414-unicamp.github.io/aulas/slides/parte01/parte01.pdf)
| 02      | Est. Descritiva  I  | [Link](http://me414-unicamp.github.io/aulas/slides/parte02/parte02.pdf)
| 03      | Est. Descritiva  II  | [Link](http://me414-unicamp.github.io/aulas/slides/parte03/parte03.pdf)
| 04    | Est. Descritiva III | [Link](https://github.com/ctruciosm/ME414-unicamp/blob/main/ME414_Aula04.pdf) | 
| 05    | Lab R | [Link](https://github.com/ctruciosm/ME414-unicamp/blob/main/ME414_LabR_01.ipynb) | 
| 06    | Exercícios | [Link]() | 
| 07 | Lab R | [Link](https://github.com/ctruciosm/ME414-unicamp/blob/main/LabR02_ME414.ipynb) |
| 08 | Bônus | [Link](https://ctruciosm.github.io/ACA-228/LabR_04#1) |
| 09 | Análise Combinatoria | [Link](https://github.com/ctruciosm/ME414-unicamp/blob/main/ME414_Aula06.pdf)
| 10 | Probabilidade | [Link](https://github.com/ctruciosm/ME414-unicamp/blob/main/ME414_Aula07.pdf)
| 11 | Probabilidade Condicional | [Link](https://github.com/ctruciosm/ME414-unicamp/blob/main/ME414_Aula08.pdf)
| 12 | Exercícios | 
| 13 | Distribuições Discretas | [Link](https://github.com/ctruciosm/ME414-unicamp/blob/main/ME414_Aula09.pdf)
| 14 | Distribuições Continuas | [Link](https://github.com/ctruciosm/ME414-unicamp/blob/main/ME414_Aula10.pdf)
| 15 | Solução da lista de exercícios | 
| 16 | Exercícios de revisão I | 
| 17 | $P_1$  | 
| 18 | Revisão da Prova  |
| 19 | Amostragem | [Link](https://github.com/ctruciosm/ME414-unicamp/blob/main/ME414_Aula11.pdf) |
| 20 | Intervalos de Confiança | [Link](https://github.com/ctruciosm/ME414-unicamp/blob/main/ME414_Aula12.pdf) | 
| 21 | Exercícios |
| 22 | Exercícios|
| 23 | Teste de Hipóteses 1 | [Link](https://github.com/ctruciosm/ME414-unicamp/blob/main/ME414_Aula13.pdf)|
| 24 | Teste de Hipóteses 2 | [Link](https://github.com/ctruciosm/ME414-unicamp/blob/main/ME414_Aula14.pdf)|
| 25 | Exercícios |
| 26 | Teste de Hipóteses 2 | [Link](https://github.com/ctruciosm/ME414-unicamp/blob/main/ME414_Aula14.pdf)|
| 27 | Teste de Hipóteses 3 | [Link](https://github.com/ctruciosm/ME414-unicamp/blob/main/ME414_Aula15.pdf)|
| 28 | Exercícios |
| 29 | $P_2$ |
| 30 | Exame |




<center>


<center>

> A vida universitária pode ter altos e baixos, se precisar conversar com alguém, seja o assunto que for, pode contar comigo. 

</center>



---- 