---
title: "ME607"
output:
  distill::distill_article: 
    fig_width: 1
    toc_float: false  
---

<center>

# Séries Temporais

## 2025.1


</center>

### Informações 

- `r emo::ji("pencil")` [Plano de desenvolvimento](documentos/2025-1_ME607A.pdf)
- `r emo::ji("teacher")` [Google Classroom  (Código da Turma caso precisarem: vckp5fm)](https://classroom.google.com/c/NzQ1MzM5NTg4NTI0?cjc=vckp5fm)
- `r emo::ji("calendar")` Terças (CB05) e quintas-feiras (CB06) das 14:00 às 16:00 horas.


### Datas Importantes

- $P_1:$ 03-04-2025.
- $P_2:$ 27-05-2025.
- $P_3:$ 01-07-2025.
- Apresentação de trabalhos: 26-06-2025.
 

</br>



### Referência Bibliográficas

#### Principais

- Brockwell, P.J & Davis, R.A. (2016). Introduction to Time Series and Forecasting, 3rd editions, Springer. [Link](https://link.springer.com/book/10.1007/978-3-319-29854-2)
- Hyndman, R.J., \& Athanasopoulos, G. (2021) Forecasting: principles and practice, 3rd edition, OTexts: Melbourne, Australia. [Link](https://otexts.com/fpp3/)
- Wei, W. (2005). Time Series Analysis: Univariate and Multivariate Methods, 2ed, Pearson


#### Complementares

- Huang, C., \& Petukhina, A. (2022). Applied Time Series Analysis and Forecasting with Python.
Springer Nature. [Link](https://link.springer.com/book/10.1007/978-3-031-13584-2)
- Krispin, R. (2019). Hands-On Time Series Analysis with R: Perform time series analysis and forecasting using R. Packt Publishing Ltd.
- Morettin, P.A, \& Toloi, C.M.C. (2006). Análise de Séries Temporais, 2ed, Blucher.
- Shumway, R. H., & Stoffer, D. S. (2019). Time series: a data analysis approach using R. Chapman and Hall/CRC.




### **Cronograma**

No título do tópico encontra-se o link para os slides.


| Data  | Tópico                         | Aula |
|:-----:|:-------------------------------|--------|
| 25-02 | [Introdução e conceitos básicos](https://ctruciosm.github.io/ME607-unicamp/Aula01.html) | 01 | 
| 27-02 | [Análise exploratória de dados](https://ctruciosm.github.io/ME607-unicamp/Aula02.html) | 02 | 
| 06-03 | [Decomposição](https://ctruciosm.github.io/ME607-unicamp/Aula03.html)   | 03 | 
| 11-03 | [Sazonalidade](https://ctruciosm.github.io/ME607-unicamp/Aula03b.html)   | 04 | 
| 13-03 | [Modelos básicos + Avaliação de modelos](https://ctruciosm.github.io/ME607-unicamp/Aula04.html) | 05 | 
| 18-03 | [Modelos de Regressão I](https://ctruciosm.github.io/ME607-unicamp/Aula05.html) | 06 | 
| 20-03 | [Modelos de Regressão II](https://ctruciosm.github.io/ME607-unicamp/Aula06.html) | 07 | 
| 25-03 | [Suavização Exponencial](https://ctruciosm.github.io/ME607-unicamp/Aula07.html)  | 08 |
| 27-03 | Apresentação de trabalhos V1 | 09 |
| 01-04 | [Modelos AR I](https://ctruciosm.shinyapps.io/Aula08/#/title-slide) | 10 | 
| 03-04 | $P_1$ | 11 | 
| 08-04 | [Modelos AR II](https://ctruciosm.github.io/ME607-unicamp/Aula09.html)   | 12 | 
| 10-04 | [Modelos AR III](https://ctruciosm.github.io/ME607-unicamp/Aula10.html)  | 13 | 
| 15-04 | [Modelos MA I](https://ctruciosm.shinyapps.io/Aula11/#/title-slide) | 14 |
| 17-04 | [Modelos MA II](https://ctruciosm.github.io/ME607-unicamp/Aula11.html) | 15 |
| 21/04--30/04 | São Paulo School of Advanced Science in High-DImensional Modeling | |
| 06-05 | [Modelos ARMA](https://ctruciosm.github.io/ME607-unicamp/Aula12.html)  | 16 | 
| 08-05 | [Modelos ARIMA](https://ctruciosm.github.io/ME607-unicamp/Arima.html)  | 17 | 
| 13-05 | [Modelos SARIMA](https://ctruciosm.github.io/ME607-unicamp/Sarima.html)  | 18 | 
| 15-05 | Apresentação de trabalhos V2 | 19 |
| 20-05 | Avaliação de curso |  | 
| 22-05 | [Seleção de Modelos](https://ctruciosm.github.io/ME607-unicamp/Selecao.html) | 20 | 
| 27-05 | $P_2$ | 21 | 
| 29-05 | Revisão $P_2$ | 22 |
| 03-06 | [Modelos (S)ARIMAX](https://github.com/ctruciosm/ctruciosm.github.io/blob/master/datasets/SARIMAX.ipynb)   | 23 | 
| 05-06  | [Modelos de Volatilidade I](https://github.com/ctruciosm/ctruciosm.github.io/blob/master/datasets/IntroARCH.ipynb)   | 24 | 
| 10-06 | [Modelos de Volatilidade II](https://github.com/ctruciosm/ctruciosm.github.io/blob/master/datasets/GARCH.ipynb)  | 25 | 
| 12-06 | [Modelos de Volatilidade III](https://github.com/ctruciosm/ctruciosm.github.io/blob/master/datasets/LeverageGARCH.ipynb)  | 26 | 
| 17-06 | [Medias de Risco](https://github.com/ctruciosm/ctruciosm.github.io/blob/master/datasets/VaRES.ipynb) | 27 | 
| 24-06 | [Modelos Hierárquicos](datasets/STH.nb.html)  | 28 | 
| 26-06 | Apresentação de trabalhos V3 (Final) | 29 |
| 01-07 | $P_3$ | 30 | 
| 15-07 | Exame | 31 | 
<center>

> A vida universitária pode ter altos e baixos, se precisar conversar com alguém, seja o assunto que for, pode contar comigo. 

</center>



---- 