---
title: "ME715"
output:
  distill::distill_article: 
    fig_width: 1
    toc_float: false  
---

<center>

# Econometria

## 2024.2


</center>



As datas das provas e apresentação do trabalho já estão definidas. Programe-se com antecedência. 

- $P_1$: **01/10**
- $P_2$: **28/11**  
- Exame: **10/12**  



</br>

### Informações 


- `r emo::ji("pencil")` [Plano de desenvolvimento (PDD)](https://github.com/ctruciosm/ME715-unicamp/blob/master/ME715A_Ementa_2024S2.pdf) 
- `r emo::ji("teacher")` [Google Classroom](https://classroom.google.com/c/NzAxMjU1MDYyNzUy?cjc=whzw3lb)  (Código da Turma caso precisarem: whzw3lb)
- `r emo::ji("calendar")` Terças e quintas-feiras das 10h às 12h no PB02

</br>

### Referência Bibliográficas


#### Básica

- Wooldridge, J. (2023). Introduçao a Econometria: Uma abordagem econometrica. 7ed. Cengage Lerning.
- Heiss, F. (2020). Using R for Introductory Econometrics. 2ed.
- Heiss, F., \& Brunner, D. (2022). Using Python for Introductory Econometrics.
- Heiss, F., \& Brunner, D. (2023). Using Julia for Introductory Econometrics.

#### Complementar

- Greene, W. H. (2003). Econometric Analysis. Pearson Education.
- Johnston, J., & DiNardo, J. (1997). Econometric Methods. Mc Graw Hill, 4ed
- [Hanck, C., Arnold, M., Gerber, A., and Schmelzer, M. (2023). Introduction to Econometrics with R (Online book)](https://www.econometrics-with-r.org/)
-  Hill, R. C., Griffiths, W. E., & Judge, G. G. (2010). Econometria. Saraiva, 3ed
-  Stock, J. H., & Watson, M. W. (2020). Introduction to Econometrics. Pearson, 4ed (Global)


### **Cronograma**


| Aula  | Assunto                | Link |
|:-----:|:-----------------------|:----:|
| 01     | Introdução  | [Link](https://ctruciosm.github.io/ME715-unicamp/ME715_Aula01.html#/title-slide) |
| 02     | Lab 01 |     |
| 03     | Revisão RLM  | [Link](https://ctruciosm.github.io/ME715-unicamp/ME715_Aula02.html#/title-slide)
| 04     | Revisão RLM II  | [Link](https://ctruciosm.github.io/ME715-unicamp/ME715_Aula03.html#/title-slide)|    
| 05     | Lab 02 |     |
| 06     | Revisão RLM III  | [Link](https://ctruciosm.github.io/ME715-unicamp/ME715_Aula04.html#/title-slide)
| 07     | Variáveis irrelevantes, omitidas e multicolinearidad | [Link](https://ctruciosm.github.io/ME715-unicamp/ME715_Aula05.html#/title-slide)
| 08     | Lab 03 |     |
| 09     | Heterocedasticidade e erros autocorrelacionais | [Link](https://ctruciosm.github.io/ME715-unicamp/ME715_Aula06.html#/title-slide)
| 10     | Minimos Quadrados Generalizados | [Link](https://ctruciosm.github.io/ME715-unicamp/ME715_Aula07.html#/title-slide)
| 11     | Lab 04 |     |
| 12     | Problemas adicionais de especificação | [Link](https://ctruciosm.github.io/ME715-unicamp/ME715_Aula08.html#/title-slide)
| 13     | Lab 05 |     |
| 14     | Exercicios |     |
| 15     | $P_1  |
| 16     | Revisão $P_1$ |
| 17     | Variáveis Instrumentais | [Link](https://ctruciosm.github.io/ME715-unicamp/ME715_Aula09.html#/title-slide)
| 18     | Modelos SUR | [Link](https://ctruciosm.github.io/ME715-unicamp/ME715_Aula10.html#/title-slide)
| 19     | Equações simultâneas | [Link](https://ctruciosm.github.io/ME715-unicamp/ME715_Aula11.html#/title-slide)
| 20     | Dados tranversais agrupados |  [Link](https://ctruciosm.github.io/ME715-unicamp/ME715_Aula12.html#/title-slide)
| 21     | Dados em painel | [Link](https://ctruciosm.github.io/ME715-unicamp/ME715_Aula13_JD.html#/title-slide)
| 22     | GMM  | [Link](https://ctruciosm.github.io/ME715-unicamp/ME715_GMM.html#/title-slide)
| 23     | MQNL | [Link](https://ctruciosm.github.io/ME715-unicamp/ME715_MQNL.html#/title-slide)
| 24     | Bootstrap | | [Link](https://ctruciosm.github.io/ME715-unicamp/ME715_Bootstrap.html#/title-slide)
| 25     | Seminário 1| 
| 26     | Seminário 2  | 
| 27     | Seminário 3  | 
| 28     | Seminário 4  | 
| 29     | Seminário 5  | 
| 30     | Exame




<center>

> A vida universitária pode ter altos e baixos, se precisar conversar com alguém, seja o assunto que for, pode contar comigo. 

</center>


---- 