---
title: "ME731"
output:
  distill::distill_article: 
    fig_width: 1
    toc_float: false  
---

<center>

# Métodos em Análise Multivariada

## 2022.2

</center>

As datas das provas já estão definidas. Programe-se com antecedência. 

- $P_1$: **26-05-2022**
- $P_2$: **14-07-2022** 
- Exame: **26-07-2022**

</br>

`r emo::ji("pencil")` [Plano de Ensino](2022-2/Plano_MAD211_2022_1.pdf) 


`r emo::ji("teacher")` [Google Classroom](https://classroom.google.com/c/NDI5NTM4Njk3ODg1?cjc=bc2jc5v)  (Código da Turma caso precisarem: bc2jc5v)

</br>

**Horários**    

`r emo::ji("calendar")` Segundas e Quartas das 16:00 às 18:00 na sala **MOD35**



### **Material e Aulas**

- [Livro de R em português](http://leg.ufpr.br/Rpira/Rpira.pdf) 
- [Livro Online: R for Data Science](https://r4ds.had.co.nz) 


### **Cronograma**

O cronograma dos tópicos a serem abordados na discplina está definido embaixo (pequenas alterações poderão ser feitas). No título do tópico encontra-se o link do video das turmas anteriores (que não necessáriamente será o mesmo mas serve de ajuda para poderem estudar), bem como slides e adicionais das turmas anteriores.


| Data  | Tópico                         | Aula |
|:-----:|:-------------------------------|--------|
| 15-08-2022     | Apresentação + EDA  | 01 | 
| 17-08-2022     | Vetores Aleatórios   | 02 | 
| 22-08-2022     | Distribuição Normal Multivariada I  | 03 | 
| 24-08-2022     | Distribuição Normal Multivariada II  | 04 | 
| 29-08-2022     | Distribuição Normal Multivariada III  | 05 | 
| 31-08-2022     | MANOVA I  | 06 | 
| 05-09-2022     | MANOVA II  | 07 | 
| 12-09-2022     | MANOVA III  | 08 | 
| 14-09-2022     | ACP I  | 09 | 
| 19-09-2022     | ACP II   | 10 | 
| 21-09-2022     | ACP III  | 11 | 
| 26-09-2022     | AF I  | 12 | 
| 28-09-2022     | AF II   | 13 | 
| 03-10-2022     | AF III   | 14 | 
| 05-10-2022     | AF IV  | 15 | 
| 10-10-2022     | $P_1$   | 16 |
| 17-10-2022     | AC I  | 17 | 
| 19-10-2022     | AC II  | 18 | 
| 24-10-2022     | ACC I  | 19 | 
| 26-10-2022     | ACC II  | 20 | 
| 31-10-2022     | ACC III   | 21 | 
| 07-11-2022     | AD I  | 22 | 
| 09-11-2022     | AD II   | 23 | 
| 14-11-2022     | AD III | 24 | 
| 16-11-2022     |   | 25 | 
| 21-11-2022     |   | 26 | 
| 23-11-2022     |   | 27 | 
| 28-11-2022     | Apresentação de Trabalhos   | 28 | 
| 30-11-2022     | Apresentação de Trabalhos   | 29 | 
| 05-12-2022     |  | 30 | 
| 07-12-2022     | $P_2$   | 31 | 
| 19-12-2022     | Exame  |  | 

<center>

> A vida universitária pode ter altos e baixos, se precisar conversar com alguém, seja o assunto que for, pode contar comigo. 

</center>



---- 