---
title: "ME731"
output:
  distill::distill_article: 
    fig_width: 1
    toc_float: false  
---

<center>

# Métodos em Análise Multivariada

## 2022.2

</center>

### Datas Importantes


- **10/10:** Prova 1.
- **21 a 23/11:** Trabalho final.
- **30/11:** Prova 2.
- **19/12:** Exame Final.

</br>

### Informações 

- `r emo::ji("pencil")` [Plano de desenvolvimento](https://github.com/ctruciosm/ctruciosm.github.io/blob/master/documentos/ME731_Ementa_2022S2.pdf)
- `r emo::ji("teacher")` [Google Classroom  (Código da Turma caso precisarem: f54eaol)](https://classroom.google.com/c/NTM3ODYxMzYyMTIz?cjc=f54eaol)
- `r emo::ji("calendar")` Segundas e quartas das 16:00 às 18:00 no CB15
- PED: Fernando Henrique Sousa Barreto <f234963@dac.unicamp.br> 
- Monitoria: Quartas-feiras 13hrs na sala 125 do IMECC


### **Cronograma**

O cronograma dos tópicos a serem abordados na discplina está definido embaixo (pequenas alterações poderão ser feitas). No título do tópico encontra-se o link para os slides.


| Data  | Tópico                         | Aula |
|:-----:|:-------------------------------|--------|
| 15-08-2022     | [Apresentação + EDA](https://ctruciosm.github.io/ME731/Aula_01)  | 01 | 
| 17-08-2022     | [Vetores Aleatórios](slides/Aula_02.pdf)   | 02 | 
| 22-08-2022     | Apresentação do Trabalho 1  | 03 | 
| 24-08-2022     | [Distribuição Normal Multivariada I](slides/Aula_04.pdf)  | 04 | 
| 29-08-2022     | [Distribuição Normal Multivariada II](slides/Aula_05.pdf)  | 05 | 
| 31-08-2022     | [Distribuição Normal Multivariada III](slides/Aula_06.pdf)  | 06 | 
| 05-09-2022     | MANOVA I  | 07 | 
| 12-09-2022     | MANOVA II  | 08 | 
| 14-09-2022     | MANOVA III   | 09 | 
| 19-09-2022     | Componentes Principais I   | 10 | 
| 21-09-2022     | Componentes Principais II  | 11 | 
| 26-09-2022     | Componentes Principais III  | 12 | 
| 28-09-2022     | Análise Fatorial I   | 13 | 
| 03-10-2022     | Análise Fatorial II   | 14 | 
| 05-10-2022     | Análise Fatorial III  | 15 | 
| 10-10-2022     | $P_1$   | 16 |
| 17-10-2022     | Análise de correspondência I  | 17 | 
| 19-10-2022     | Análise de correspondência II  | 18 | 
| 24-10-2022     | Análise de correspondência III  | 19 | 
| 26-10-2022     | Correlação Canônica I  | 20 | 
| 31-10-2022     | Correlação Canônica II   | 21 | 
| 07-11-2022     | Correlação Canônica III  | 22 | 
| 09-11-2022     | Análise Discriminante I   | 23 | 
| 14-11-2022     | Análise Discriminante II | 24 | 
| 16-11-2022     | Análise Discriminante III   | 25 | 
| 21-11-2022     | Apresentação de Trabalhos  | 26 | 
| 23-11-2022     | Apresentação de Trabalhos  | 27 | 
| 30-11-2022     | $P_2$   | 29 | 
| 19-12-2022     | Exame  | 30 | 

<center>

> A vida universitária pode ter altos e baixos, se precisar conversar com alguém, seja o assunto que for, pode contar comigo. 

</center>



---- 