---
title: "MI628 / ME920"
output:
  distill::distill_article: 
    fig_width: 1
    toc_float: false  
---

<center>

# MI628: Inferência Causal
# ME920: Introdução à Inferência Causal

## 2024.1


</center>

### Informações 

- `r emo::ji("pencil")` [Plano de desenvolvimento]()
- `r emo::ji("teacher")` [Google Classroom]()
- `r emo::ji("calendar")` Terças e quintas-feiras das 10:00 às 12:00 no PB02.


### Datas Importantes

- $P_1:$ 25-04-2024.
- $P_2:$ 20-06-2024.
- **Seminários:** 25-06-2024 e 27-06-2024
- **Exame:** 09-07-2024.
 

</br>



### Referência Bibliográficas

#### Livro texto

- Ding, P. (2024). A First Course in Causal Inference, Chapman and Hall/CRC. [Link](https://arxiv.org/abs/2305.18793)

#### Complementares


- Hernán, M.A., &  Robins, J. M. (2020). Causal Inference: What If. Boca Raton: Chapman & Hall/CRC [Link](https://www.hsph.harvard.edu/miguel-hernan/wp-content/uploads/sites/1268/2024/01/hernanrobins_WhatIf_2jan24.pdf)
- Cunningham, S. (2021). Causal Inference: The mixtape. Yale University Press [Link](https://mixtape.scunning.com/)
- Pearl, J., Glymour, M., & Jewell, N. P. (2016). Causal Inference in Statistics: A primer. John Wiley & Sons.
- Pearl, J. (2009). Causality: Models, reasoning and inference. Cambridge, UK: Cambridge University Press.


### **Cronograma**

No título do tópico encontra-se o link para os slides.


| Data  | Tópico                         | Aula |
|:-----:|:-------------------------------|--------|
| 29-02-2024   | [Introdução](https://ctruciosm.github.io/MI628-unicamp/MI628_Aula01) | 01 | 
| 05-03-2024   | [Resultados Potenciais e FRT](https://ctruciosm.github.io/MI628-unicamp/MI628_Aula02)  | 02 | 
| 07-03-2024   | [Neyman](https://ctruciosm.github.io/MI628-unicamp/MI628_Aula03) | 03 | 
| 12-03-2024   |  Lista 1 | 04 | 
| 14-03-2024   | [Estratificação](https://ctruciosm.github.io/MI628-unicamp/MI628_Aula04) | 05 | 
| 19-03-2024   | [Rerandomização](https://ctruciosm.github.io/MI628-unicamp/MI628_Aula05) | 06 | 
| 21-03-2024   | Lista 2 | 07 | 
| 26-03-2024   | [RMPE](https://ctruciosm.github.io/MI628-unicamp/MI628_Aula06) | 08 | 
| 02-04-2024   | [Experimentos Randomizados](https://ctruciosm.github.io/MI628-unicamp/MI628_Aula07)  | 09 | 
| 04-04-2024   | Lista 4 | 10 | 
| 09-04-2024   | Lista 3 | 11 | 
| 11-04-2024   | [Estudos observacionais](https://ctruciosm.github.io/MI628-unicamp/MI628_Aula08)  | 11 | 
| 16-04-2024   | [Propensity Score](https://ctruciosm.github.io/MI628-unicamp/MI628_Aula09) | 12 | 
| 18-04-2024   | [DR](https://ctruciosm.github.io/MI628-unicamp/MI628_Aula10) | 13 | 
| 23-04-2024   | Estudo em grupo pre-prova | 14 | 
| 25-04-2024   | $P_1$ | 16 | 
| 30-04-2024   |[$\tau_T$](https://ctruciosm.github.io/MI628-unicamp/MI628_Aula11) | 17 | 
| 02-05-2024   |[Propensity Score em Regressão](https://ctruciosm.github.io/MI628-unicamp/MI628_Aula12)  | 18 | 
| 07-05-2024   | [Matching](https://ctruciosm.github.io/MI628-unicamp/MI628_Aula13) | 19 | 
| 09-05-2024   |  | 20 | 
| 14-05-2024   |  | 21 | 
| 16-05-2024   |  | 22 | 
| 21-05-2024   |  | 23 | 
| 23-05-2024   |  | 24 | 
| 28-05-2024   |  | 25 | 
| 04-06-2024   |  | 26 | 
| 06-06-2024   |  | 27 | 
| 11-06-2024   |  | 28 | 
| 13-06-2024   |  | 29 | 
| 18-06-2024   |  | 30 | 
| 20-06-2024   | $P_2$ | 31 | 
| 25-06-2024   | Seminários | 32 | 
| 27-06-2024   | Seminários | 33 | 
| 09-07-2024   | Exame | 34 | 

<center>

> A vida universitária pode ter altos e baixos, se precisar conversar com alguém, seja o assunto que for, pode contar comigo. 

</center>



---- 