---
title: "Modelos de Regressão e Previsão"
output:
  html_document:
    fig_width: 1
    toc_float: false    
---

<style type="text/css">
.nav.navbar-nav.navbar-right a {
    color: white;
}
.navbar {
  background-color: #00695c;
  border-color:black;
  icon-color:white;
}
.navbar-brand {
color:black!important;
}
body{ /* Normal  */
      font-size: 15px;
  }
h1.title {
  font-size: 32px;
}
h3 { /* Header 3 */
  font-size: 24px;
  color: darkgreen;
}
</style>

<style>
a:link {
    color: darkgreen;
}
a:visited {
    color: darkgreen;
}
a:hover {
    color: blue;
}
.column-f1{
  float: left;
  width: 20%;
  text-align: left;
}
.column-f2{
  float: right;
  width: 20%;
  text-align: right;
}
</style>

----

**Notas da P1 + Seminário liberadas!**
[Notas](MRP/NOTAS_MRP.xlsx) 


**Lista 2 Liberada!**

[Lista 1](MRP/Lista1.pdf)  

[Lista 2](MRP/Lista2.pdf)  

**Material de R**

[Livro](http://leg.ufpr.br/Rpira/Rpira.pdf) 


**Links importantes**

[Plano de Ensino](MRP/PlanoEnsino.pdf) 

[YouTube Channel](https://www.youtube.com/playlist?list=PLrqJCLOY0EkDnnNuVz4FEKXoM6nDqxrgu) 

[Google Classroom](https://classroom.google.com/c/MjUwMTAwMjUyOTcy?cjc=pad4hj5)  (Código da Turma caso precisarem: gde3vhhxvi)

[Link Google Meet](https://meet.google.com/urk-dtqw-trp)  


**Horários**

Terças e Quintas das 16:40 às 18:20 (Turma B)
Terças e Quintas das 18:30 às 20:10 (Turma D)


**Monitorias**

Monitor: Estamos sem monitor no momento


----

### **Material e Aulas**

- Os conjuntos de dados que serão utilizados durante o curso estão disponíveis [aqui](MRP/DadosMRP.zip) 
- Baixe o apêndice do livro texto [aqui](MRP/Apendice_Livro.pdf) 


| Aula   | Assunto                           | Data       | Video | Slides | Extras |
|--------|-----------------------------------|------------|-------|--------|--------|
| 1      | Intro e Reg. Linear Simples       | 07/01/2021 | [Link](https://youtu.be/Hnb2mJs6nb8)  - [Link R](https://youtu.be/N360-J0MWwk)    | [link](MRP/Aula01.pdf)        | [Script R](MRP/EDA_Aula1.R)         |
| 2      | RLS: Estimação                    | 12/01/2021 |  [Link](https://youtu.be/GCK-38OrXWc)      |   [link](MRP/Aula02.pdf)      |   [Script R](MRP/RLS_Aula2.R)       |
| 3      | RLS: Interpretação e Propriedades | 14/01/2021 | [Link](https://youtu.be/fsWB6CG-Ri0)       |   [link](MRP/Aula03.pdf)      |  [Script R](MRP/RLS_Aula3.R)  |
| 4      | Laboratorio de R Parte I| 19/01/2021 |  [Link](https://youtu.be/d_rR36_GXaA)      |        |   [Script R](MRP/Lab01.R)     |
| 5      | Modelo de Regressão Linear Multipla (MRLM) | 21/01/2021 |  [Link](https://youtu.be/U9aQJNsG_K4)      |   [link](MRP/Aula05.pdf)      | [Script R](MRP/MRLM_Aula5.R)        |
| 6      | MRLM: Inferência | 26/01/2021 |   [Link](https://youtu.be/fcb2RvJcWi4)     |   [link](MRP/Aula06.pdf)      |  [Script R](MRP/MRLM_Aula6.R)       |
| 7      | Laboratorio de R Parte II | 28/01/2021 | [Link](https://youtu.be/dnH9x0cHz0A)        |  [Gabarito L1](MRP/Lista1_Gabarito.pdf)       |  [Script R](MRP/Gabarito_Lista1_Codigos.R)      |
| 8      | MRLM: Tópicos adicionais | 02/02/2021 |  [Link](https://youtu.be/avw-4zmABqA)     |  [link](MRP/Aula08.pdf)      |   [Script R](MRP/Aula08.R)     |
| 9      | MRLM: variáveis qualitativas e intereção | 02/02/2021 |  [Link](https://youtu.be/Nt6-wrEJVCg)      |  [link](MRP/Aula09.pdf)   [Gabarito L2](MRP/Lista2_Gabarito.pdf)    |  [Script R](MRP/Aula09.R)      |  
| 10      | MRLM: verificação das hipóteses | 09/02/2021 | [Link](https://youtu.be/xLJ5KI3YfJ4)       |   [link](MRP/Aula10.pdf)      |      |  
| 11      | MRLM: verificação das hipóteses II + Lab de R  | 11/02/2021 |   [Link](https://youtu.be/V5nl51DRVnw)      |   [link](MRP/Aula11.pdf)        |    [lab R](https://youtu.be/t-oSK9At9P8) [Script R](MRP/LabR-3.R)   |  
| 12      | MQO e Séries Temporais | 23/02/2021 |   [Link](https://youtu.be/-TK27cb2QGY)     |   [link](MRP/Aula12.pdf)        |      | 
| 13      | MQO e Séries Temporais II | 25/02/2021 |  [Link](https://youtu.be/Oh84Cy6oGCw)         |   [link](MRP/Aula13.pdf)          |      | 
| 14      | MQO e Séries Temporais III | 02/03/2021 |  [Link](https://youtu.be/qZAtaarop0c)     |  [link](MRP/Aula14.pdf)            |      | 
| 15      | Seminários | 04/03/2021 |       |          |      | 











---- 
