---
title: "Research"
output:
  distill::distill_article:
    toc: false
---

**Research Interest:** Bootstrap procedures for dependent data; general dynamic factor models; high dimensional data; risk measures and portfolio allocation; robust procedures in time series; statistical learning for business, economics and finance.



```{r panelset, layout='l-page', echo=FALSE}
xaringanExtra::use_panelset()
xaringanExtra::style_panelset_tabs(foreground = "honeydew", background = "#0F2E3D")
```


::::: {.panelset}

::: {.panel}

#### Publications {.panel-name}

#### PEER-REVIEWED PUBLICATIONS

<ol reversed>

<li> [*A Comparison of Methods for Forecasting Value-at-Risk and Expected Shortfall of Cryptocurrencies.*](https://onlinelibrary.wiley.com/doi/abs/10.1002/for.2929) **Journal of Forecasting** (2023) [with James W. Taylor] [`CODES`](https://github.com/ctruciosm/CryptoForeComb) \medskip </li>


<li> [*Forecasting Conditional Covariance Matrices in High-Dimensional Time Series: a General Dynamic Factor Approach.*](https://www.tandfonline.com/doi/abs/10.1080/07350015.2021.1996380?journalCode=ubes20) **Journal of Business and Economic Statistics** (2023) [with João Mazzeu, Marc Hallin, Luiz Hotta, Pedro Valls and Mauricio Zevallos] \medskip </li>



<li> [*Forecasting Value-at-Risk and Expected Shortfall in Large Portfolios: a General Dynamic Factor Model Approach*](https://www.sciencedirect.com/science/article/abs/pii/S2452306221000563). **Econometrics and Statistics** (2021). [with Marc Hallin]  [`CODES`](https://github.com/ctruciosm/GDFM-CHF-VaRES) </li> \medskip

<li> [*Robustness and the general dynamic factor model with infinite-dimensional space: identification, estimation, and forecasting*](https://www.sciencedirect.com/science/article/pii/S0169207020301540). **International Journal of Forecasting** (2020). [with João Mazzeu, Luiz Hotta, Pedro Valls and Marc Hallin]  </li> \medskip

<li> [*Value-at-Risk and Expected Shortfall in Cryptocurrencies’ Portfolio: A Vine Copula–based Approach*](https://www.tandfonline.com/doi/abs/10.1080/00036846.2019.1693023?journalCode=raec20). **Applied Economics** (2020). [with Aviral Tiwari and Faisal Alqahtani] [`CODES`](https://github.com/ctruciosm/CryptoCopVaRES) </li>  \medskip

<li> [*Covariance prediction in large portfolio allocation*](https://www.mdpi.com/2225-1146/7/2/19). **Econometrics** (2019). [with Mauticio Zevallos, Luiz Hotta and André P. Santos]  </li> \medskip

<li> [*On the robustness of the principal volatility components*](https://www.sciencedirect.com/science/article/abs/pii/S0927539819300386). **Journal of Empirical Finance** (2019). [with Luiz Hotta and Pedro Valls]  [`R PACKAGE`](https://github.com/ctruciosm/Robpvc) </li> \medskip

<li> [*Forecasting Bitcoin risk measures: A robust approach*](https://www.sciencedirect.com/science/article/abs/pii/S0169207019300184). **International Journal of Forecasting** (2019). [`R PACKAGE`](https://cran.r-project.org/package=RobGARCHBoot) </li> \medskip

<li> [*Inference in (M)GARCH Models in the Presence of Additive Outliers: Specification, Estimation and Prediction*](https://link.springer.com/chapter/10.1007/978-3-319-94015-1_8). In Lavor, C. and Neto, F. A. M. G., editors, Advances in Mathematics and Applications. **Springer**. (2018). [with Luiz Hotta] </li> \medskip

<li> [*Robust Bootstrap Densities for Dynamic Conditional Correlations: Implications for Portfolio Selection and Value-at-Risk*](https://www.tandfonline.com/doi/abs/10.1080/00949655.2018.1462811?journalCode=gscs20). **Journal of Statistical Computing and Simulation** (2018). [with Luiz Hotta and Esther Ruiz] </li> \medskip

<li> [*Robust bootstrap forecast densities for GARCH returns and volatilities*](https://www.tandfonline.com/doi/abs/10.1080/00949655.2017.1359601?journalCode=gscs20). **Journal of Statistical Computing and Simulation** (2017). [with Luiz Hotta and Esther Ruiz] [`R PACKAGE`](https://cran.r-project.org/package=RobGARCHBoot) </li> \medskip

<li> [*Bootstrap prediction in univariate volatility models with leverage effect*](https://www.sciencedirect.com/science/article/abs/pii/S03784754150013303). **Mathematics and Computers in Simulation** (2016). [with Luiz Hotta] </li> \medskip

</ol>

##### OTHER PUBLICATIONS

<ol reversed>

<li> [*Factors that influence in the academic performance of the students of the Faculty of Mathematical sciences of the Universidad Nacional Mayor de San Marcos*](https://140.82.11.112/index.php/ECIPERU/article/view/336/324). **ECI PERU** (2009). [with Estela Ponce Aruneri] </li> 

</ol>

:::

::: {.panel}

#### Working Papers {.panel-name}

#### WORKING PAPERS

<ol reversed>

<li> *Using hierarchical risk parity in the Brazilian market: An out-of-sample analysis..* [with Felipe Reis, Anderson Sobreira and Boris Asrilhant] Submitted _Brazilian Review of Finance_ \medskip </li>

<li> *Does portfolio resampling really improve out-of-sample performance? Evidence from the Brazilian and US marketst.* [with André Oliveira and Pedro Valls] Submitted _Journal of Banking and Finance_ \medskip </li>


</ol>

:::

::: {.panel}

#### Ongoing {.panel-name}

#### ONGOING WORK


<ol reversed>


<li> *Forecasting VaR and ES through Markov Switching GARCH Models.* [with Luiz K. Hotta, Mauricio Zevallos and Pedro Valls] \medskip </li>

<li> *A note about calibration tests for VaR and ES.* [with Luiz K. Hotta and Mauricio Zevallos] \medskip </li>


</ol>

:::


:::::

