---
title: "Teaching"
output:
  distill::distill_article:
    toc: false
---


```{r panelset, layout='l-page', echo=FALSE}
xaringanExtra::use_panelset()
xaringanExtra::style_panelset_tabs(foreground = "honeydew", background = "#0F2E3D")
```



::::: {.panelset}


::: {.panel}

#### Graduate {.panel-name}

- [Seminários de Estatística](MI908.html) (2025/1)
- [Seminários de Probabilidade e Estatística](MI910.html) (2024/2)
- [Causal Inference](MI628.html) (2024/1)



:::

::: {.panel}

#### Undergraduate {.panel-name}

- **UNICAMP**
  - [Econometrics](ME715.html) (2023/2, 2024/2)
  - [Time Series](ME607.html) (2023/1, 2025/1)
  - [Multivariate Statistical Analysis](ME_731.html) (2022/2).
  - [Statistics for Experimentalist](ME414.html) (2022/2, 2023/2, 2024/2).
- **UFRJ**
  - [Quantitative Methods for Business Administration](ACA124.html) (2022/1).
  - [Statistics for Business](MAD211.html) (2020/2, 2021/1, 2021/2, 2022/1).
  - [Forecasting and Regression Models](ACA228.html) (2020/1, 2020/2, 2021/2, 2021/2).
- **UFABC**
  - Introduction to Probability and Statistics (2020/1).
- **T.A**
  - Probability, EESP-FGV (2018/1).
  - Statistics for experimentalist, UNICAMP (2015/2, 2012/2).
  - Elementar Statistics, UNICAMP (2012/2)
  - Introduction to probability models, UNICAMP (2012/1).
  - Statistical Computing, UNMSM (2010/1).

:::

::: {.panel}

#### Short Courses {.panel-name}

- Estadística y Machine Learning en economía y finanzas: el caso de selección de carteras. UNMSM 2025. [Slides 1](https://ctruciosm.github.io/PortfolioAllocation/PortfolioAllocation_UNMSM#/title-slide) - [Slides 2](https://ctruciosm.github.io/PortfolioAllocation/PortfolioAllocation_Shrinkage#/title-slide) - [Slides 3](https://ctruciosm.github.io/PortfolioAllocation/UNICAMP#/title-slide)
- Julia para ciência de dados. Semana da Matemática Aplicada da UNICAMP 2025. [Slides](https://ctruciosm.github.io/JuliaCrashCourses/Intro.html#/title-slide)
- Risk-based Portfolio Allocation Strategies. Semana da Estatística UFJF 2024, Juiz de Fora - MG- [Slides](https://ctruciosm.github.io/PortfolioAllocation/PortfolioAllocation_UFJF)
- Risk-based Portfolio Allocation Strategies. ENCPOS2024, Campinas - SP- [Slides](https://ctruciosm.github.io/PortfolioAllocation/PortfolioAllocation)
- Introdução à mineração de texto com R. RJ-BR, 2021. [Slides 1](https://ctruciosm.github.io/IMTR/IMTR) -- [Slides 2](https://ctruciosm.github.io/IMTR/IMTR2) --
[Slides 3](https://ctruciosm.github.io/IMTR/IMTR3) -- [Slides 4](https://ctruciosm.github.io/IMTR/IMTR4)
- Modelling and forecasting financial risk measures, II Symposium on Mathematics and Applied Mathematics. Arequipa-Perú, 2019.
- Special topics in R software: Graduate program, National University of San Marcos. Lima-Perú, 2016.
- Special topics in R software: Ricardo Palma University. Lima-Perú, 2016.
- Data manipulation and data visualization in R: 17th Statistics week, University of Campinas. Campinas-Brazil, 2015.

:::


:::::

